<x-layout>
    <x-slot:title>{{ $guide->exists ? 'Edit' : 'Tambah' }} Panduan — MVPWarehouse</x-slot:title>
    <x-slot:headerTitle>{{ $guide->exists ? 'Edit' : 'Tambah' }} Panduan</x-slot:headerTitle>
    <div class="mx-auto max-w-6xl">
        @if($errors->any())<div class="mb-5 rounded-lg border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700">@foreach($errors->all() as $error)<p>{{ $error }}</p>@endforeach</div>@endif
        @if(session('success'))<div class="mb-5 rounded-lg border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm text-emerald-800">{{ session('success') }}</div>@endif
        <form method="POST" enctype="multipart/form-data" action="{{ $guide->exists ? route('admin.help-guides.update', $guide) : route('admin.help-guides.store') }}" class="space-y-5" id="guideForm">
            @csrf @if($guide->exists) @method('PUT') @endif
            <div class="grid gap-5 lg:grid-cols-[.8fr_1.2fr]">
                <div class="space-y-5 rounded-xl border border-slate-200 bg-white p-6">
                    <div><label class="mb-1 block text-xs font-semibold text-slate-600">Judul</label><input name="title" value="{{ old('title', $guide->title) }}" required class="w-full rounded-lg border border-slate-200 px-3 py-2 text-sm outline-none focus:border-corpblue-500"></div>
                    <div><label class="mb-1 block text-xs font-semibold text-slate-600">Kategori</label><input name="category" value="{{ old('category', $guide->category ?: 'Gudang') }}" required class="w-full rounded-lg border border-slate-200 px-3 py-2 text-sm outline-none focus:border-corpblue-500"></div>
                    <div><label class="mb-1 block text-xs font-semibold text-slate-600">Role</label><select name="audience_role" class="w-full rounded-lg border border-slate-200 px-3 py-2 text-sm outline-none focus:border-corpblue-500"><option value="all" @selected(old('audience_role', $guide->audience_role) === 'all')>Semua Role</option>@foreach(['gudang' => 'Gudang', 'hr' => 'HR', 'director' => 'Direktur', 'admin' => 'Admin'] as $value => $label)<option value="{{ $value }}" @selected(old('audience_role', $guide->audience_role) === $value)>{{ $label }}</option>@endforeach</select></div>
                    <div><label class="mb-1 block text-xs font-semibold text-slate-600">Deskripsi singkat</label><textarea name="description" rows="4" class="w-full resize-none rounded-lg border border-slate-200 px-3 py-2 text-sm outline-none focus:border-corpblue-500">{{ old('description', $guide->description) }}</textarea></div>
                    <div><label class="mb-1 block text-xs font-semibold text-slate-600">Urutan</label><input type="number" min="0" name="sort_order" value="{{ old('sort_order', $guide->sort_order) }}" class="w-full rounded-lg border border-slate-200 px-3 py-2 text-sm outline-none focus:border-corpblue-500"></div>
                    <div><label class="mb-1 block text-xs font-semibold text-slate-600">Screenshot {{ $guide->exists ? '(opsional)' : '' }}</label><input id="imageInput" type="file" name="image" accept="image/jpeg,image/png,image/webp" {{ $guide->exists ? '' : 'required' }} class="w-full text-sm"><p class="mt-1 text-[11px] text-slate-400">JPG, PNG, atau WebP maksimal 5 MB.</p></div>
                    <input type="hidden" name="markers" id="markersInput">
                    <button class="w-full rounded-lg bg-corpblue-500 px-4 py-2.5 text-sm font-semibold text-white hover:bg-corpblue-600">Simpan Draft</button>
                </div>
                <div class="rounded-xl border border-slate-200 bg-white p-6"><div class="flex items-center justify-between"><div><h3 class="text-sm font-bold text-slate-900">Editor Marker</h3><p class="mt-1 text-xs text-slate-400">Klik gambar untuk menambahkan marker bernomor.</p></div><button type="button" id="clearMarkers" class="text-xs font-semibold text-red-600">Hapus Marker</button></div><div id="editor" class="relative mt-5 min-h-64 overflow-hidden rounded-lg border border-dashed border-slate-300 bg-slate-50"><img id="previewImage" src="{{ $guide->images->first() ? Storage::disk('public')->url($guide->images->first()->image_path) : '' }}" class="{{ $guide->images->first() ? '' : 'hidden' }} block w-full" alt="Preview"><p id="emptyPreview" class="p-12 text-center text-sm text-slate-400 {{ $guide->images->first() ? 'hidden' : '' }}">Upload screenshot untuk memulai.</p></div><div id="markerFields" class="mt-5 space-y-3"></div></div>
            </div>
        </form>
    </div>
    <x-slot:scripts><script>
        const editor = document.getElementById('editor'), preview = document.getElementById('previewImage'), emptyPreview = document.getElementById('emptyPreview'), markerFields = document.getElementById('markerFields'), markersInput = document.getElementById('markersInput');
        let markers = @json($markers);
        let draggingMarker = null;
        function sync() { markersInput.value = JSON.stringify(markers); document.querySelectorAll('.guide-marker').forEach(node => node.remove()); markers.forEach((marker, index) => { const node = document.createElement('span'); node.className = 'guide-marker absolute flex h-7 w-7 -translate-x-1/2 -translate-y-1/2 cursor-move items-center justify-center rounded-full border-2 border-white bg-corpblue-500 text-xs font-bold text-white shadow-lg'; node.dataset.index = index; node.style.left = marker.x + '%'; node.style.top = marker.y + '%'; node.textContent = index + 1; editor.appendChild(node); }); markerFields.innerHTML = ''; markers.forEach((marker, index) => { markerFields.insertAdjacentHTML('beforeend', `<div class="rounded-lg border border-slate-200 bg-slate-50 p-3"><div class="flex items-center justify-between"><b class="text-xs text-corpblue-700">Marker ${index + 1}</b><button type="button" data-remove="${index}" class="text-xs text-red-600">Hapus</button></div><input data-field="title" data-index="${index}" value="${escapeHtml(marker.title || '')}" placeholder="Judul langkah" class="mt-2 w-full rounded border border-slate-200 px-2 py-1.5 text-xs"><textarea data-field="description" data-index="${index}" rows="2" placeholder="Keterangan singkat" class="mt-2 w-full resize-none rounded border border-slate-200 px-2 py-1.5 text-xs">${escapeHtml(marker.description || '')}</textarea></div>`); }); document.querySelectorAll('[data-remove]').forEach(button => button.addEventListener('click', () => { markers.splice(Number(button.dataset.remove), 1); sync(); })); document.querySelectorAll('[data-field]').forEach(field => field.addEventListener('input', () => { markers[Number(field.dataset.index)][field.dataset.field] = field.value; markersInput.value = JSON.stringify(markers); })); }
        function escapeHtml(value) { return String(value).replace(/[&<>'"]/g, character => ({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#039;','"':'&quot;'}[character])); }
        function addMarker(event) { if (event.target !== preview) return; const rect = preview.getBoundingClientRect(); markers.push({ x: ((event.clientX - rect.left) / rect.width * 100).toFixed(3), y: ((event.clientY - rect.top) / rect.height * 100).toFixed(3), title: '', description: '' }); sync(); }
        editor.addEventListener('mousedown', event => { const node = event.target.closest('.guide-marker'); if (!node) return; event.preventDefault(); draggingMarker = Number(node.dataset.index); }); document.addEventListener('mousemove', event => { if (draggingMarker === null) return; const rect = preview.getBoundingClientRect(); markers[draggingMarker].x = Math.max(0, Math.min(100, (event.clientX - rect.left) / rect.width * 100)).toFixed(3); markers[draggingMarker].y = Math.max(0, Math.min(100, (event.clientY - rect.top) / rect.height * 100)).toFixed(3); sync(); }); document.addEventListener('mouseup', () => { draggingMarker = null; });
        preview.addEventListener('dragstart', event => event.preventDefault()); preview.addEventListener('click', addMarker); document.getElementById('clearMarkers').addEventListener('click', () => { markers = []; sync(); }); document.getElementById('imageInput').addEventListener('change', event => { const file = event.target.files[0]; if (!file) return; preview.src = URL.createObjectURL(file); preview.classList.remove('hidden'); emptyPreview.classList.add('hidden'); preview.onload = sync; }); sync();
    </script></x-slot:scripts>
</x-layout>
