<x-layout>
    <x-slot:title>Kelola Bantuan — MVPWarehouse</x-slot:title>
    <x-slot:headerTitle>Kelola Bantuan</x-slot:headerTitle>
    <div class="space-y-5">
        <div class="flex items-center justify-between"><div><p class="text-sm text-slate-500">Kelola panduan visual untuk semua role.</p></div><a href="{{ route('admin.help-guides.create') }}" class="rounded-lg bg-corpblue-500 px-4 py-2.5 text-sm font-semibold text-white hover:bg-corpblue-600">Tambah Panduan</a></div>
        <div class="overflow-hidden rounded-xl border border-slate-200 bg-white"><table class="w-full text-left text-sm"><thead class="border-b border-slate-200 bg-slate-50 text-xs uppercase text-slate-500"><tr><th class="px-5 py-3">Panduan</th><th class="px-5 py-3">Role</th><th class="px-5 py-3">Status</th><th class="px-5 py-3 text-right">Aksi</th></tr></thead><tbody class="divide-y divide-slate-100">@forelse($guides as $guide)<tr><td class="px-5 py-4"><p class="font-semibold text-slate-900">{{ $guide->title }}</p><p class="text-xs text-slate-400">{{ $guide->category }}</p></td><td class="px-5 py-4 text-xs text-slate-600">{{ ucfirst($guide->audience_role) }}</td><td class="px-5 py-4"><span class="rounded-full px-2 py-1 text-[11px] font-semibold {{ $guide->status === 'published' ? 'bg-emerald-50 text-emerald-700' : ($guide->status === 'archived' ? 'bg-slate-100 text-slate-500' : 'bg-amber-50 text-amber-700') }}">{{ ucfirst($guide->status) }}</span></td><td class="px-5 py-4"><div class="flex justify-end gap-2"><a href="{{ route('admin.help-guides.edit', $guide) }}" class="text-xs font-semibold text-corpblue-600">Edit</a>@if($guide->status !== 'published')<form method="POST" action="{{ route('admin.help-guides.publish', $guide) }}">@csrf<button class="text-xs font-semibold text-emerald-600">Publish</button></form>@endif<form method="POST" action="{{ route('admin.help-guides.destroy', $guide) }}" data-confirm="Hapus panduan ini?">@csrf @method('DELETE')<button class="text-xs font-semibold text-red-600">Hapus</button></form></div></td></tr>@empty<tr><td colspan="4" class="px-5 py-10 text-center text-sm text-slate-400">Belum ada panduan.</td></tr>@endforelse</tbody></table></div>
        @if($guides->hasPages()){{ $guides->links() }}@endif
    </div>
</x-layout>
